apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minimal-api.fullname" . }}-secret
  labels:
    {{- include "minimal-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.secret.dbName | quote }}
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
